[project]
name = "Ostat OpenSCAD Projects"
uri = "https://github.com/ostat/OpenSCAD-Projects"
export-filename-prefix = "ostat"
mode = "multi"
head-extra = ''

[[model]]
file = "CncClamps_OpenSCAD/CNCClamps.scad"

[[model]]
file = "DrawerDivider_OpenSCAD/DrawerDivider.scad"

[[model]]
file = "DripTray_OpenSCAD/DripTray.scad"

[[model]]
file = "FlashlightDiffuser_OpenSCAD/FlashlightDiffuser.scad"

[[model]]
file = "leg_caps_OpenSCAD/stand.scad"

[[model]]
file = "TapeCutter_OpenSCAD/TapeCutter_OpenSCAD.scad"

[[model]]
file = "toy-stack-octahedron/toy_stack_octahedron.scad"